### ISSUE TITLE
has no possibility to track crash to other analytics

### ISSUE THREAD

**Issue by AGulev** [britzl/defold-googleanalytics#1]
For now, we have no possibility to track a crash report to another analytics system if we use Google Analytics, because GA now removes a crash file without any external callback.
https://github.com/britzl/defold-googleanalytics/blob/c6dffb4bd28d80f7369030208213a2f5f4b633ff/googleanalytics/tracker.lua#L85-L86

**Comment by britzl** [comment]
Fixed in https://github.com/britzl/defold-googleanalytics/releases/tag/1.4.0
